version: '3'

services:
  nostr-to-discord:
    build: .
    container_name: nostr-discord
    environment:
      - RELAY_URL=wss://relay.example.com
      - PUBKEY=your_public_key_here
      - EVENT_TYPES=0,1,3,7
      - DISCORD_WEBHOOK_URL=https://discord.com/api/webhooks/your_webhook_url
    restart: unless-stopped
